apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: fcs-infra
  labels:
    app.kubernetes.io/name: kafka-ui
    app.kubernetes.io/component: tooling
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka-ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kafka-ui
        app.kubernetes.io/component: tooling
    spec:
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:latest
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: local
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: kafka-service.fcs-infra.svc.cluster.local:29092
            - name: KAFKA_CLUSTERS_0_READONLY
              value: "false"
            - name: DYNAMIC_CONFIG_ENABLED
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-service
  namespace: fcs-infra
  labels:
    app.kubernetes.io/name: kafka-ui
    app.kubernetes.io/component: tooling
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: kafka-ui
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30082
