apiVersion: v1
kind: ConfigMap
metadata:
  name: fcs-campaign-local-config
  namespace: fcs-campaign
  labels:
    app.kubernetes.io/name: fcs-campaign
    environment: local
data:
  ASPNETCORE_ENVIRONMENT: "Docker"
  ASPNETCORE_URLS: "http://+:8080"
  KafkaSettings__BootstrapServers: "kafka-service.fcs-infra.svc.cluster.local:29092"
  KafkaSettings__TopicName: "audit-log-requested"
  Keycloak__Authority: "http://keycloak-service.fcs-infra.svc.cluster.local:8080/realms/conexao-solidaria"
  Keycloak__Audience: "solidarity-api"
  Observability__ServiceName: "fcs.Campaign"
  Observability__EnableOtlpExporter: "true"
  Observability__OtlpEndpoint: "http://otel-collector-service.fcs-infra.svc.cluster.local:4318"
  Observability__OtlpAuthHeader: ""
