apiVersion: apps/v1
kind: Deployment
metadata:
  name: fcs-donation-worker
  namespace: fcs-donation-worker
  labels:
    app.kubernetes.io/name: fcs-donation-worker
    app.kubernetes.io/component: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fcs-donation-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fcs-donation-worker
        app.kubernetes.io/component: worker
    spec:
      containers:
        - name: fcs-donation-worker
          image: ghcr.io/group10-tc-01/fcs-donation-worker:main
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: fcs-donation-worker-local-config
          env:
            - name: ConnectionStrings__SqlServer
              valueFrom:
                secretKeyRef:
                  name: fcs-donation-worker-local-secret
                  key: sqlserver-connection-string
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 18
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 6
---
apiVersion: v1
kind: Service
metadata:
  name: fcs-donation-worker-service
  namespace: fcs-donation-worker
  labels:
    app.kubernetes.io/name: fcs-donation-worker
    app.kubernetes.io/component: worker
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: fcs-donation-worker
  ports:
    - name: http
      port: 80
      targetPort: 8080
