apiVersion: v1
kind: ConfigMap
metadata:
  name: fcs-audit-logs-local-config
  namespace: fcs-audit-logs
  labels:
    app.kubernetes.io/name: fcs-audit-logs
    environment: local
data:
  DOTNET_ENVIRONMENT: "Docker"
  ASPNETCORE_ENVIRONMENT: "Docker"
  ASPNETCORE_URLS: "http://+:8080"
  KafkaSettings__BootstrapServers: "kafka-service.fcs-infra.svc.cluster.local:29092"
  KafkaSettings__GroupId: "fcs-audit-logs-consumer-group"
  KafkaSettings__Topics__AuditLogRequested: "audit-log-requested"
  MongoDbSettings__ConnectionString: "mongodb://mongodb-service.fcs-infra.svc.cluster.local:27017"
  MongoDbSettings__DatabaseName: "AuditLogsDb"
  MongoDbSettings__CollectionName: "audit_logs"
  Observability__ServiceName: "Fcs.Audit.Logs"
  Observability__EnableOtlpExporter: "true"
  Observability__OtlpEndpoint: "http://otel-collector-service.fcs-infra.svc.cluster.local:4318"
  Observability__OtlpAuthHeader: ""
