apiVersion: v1
kind: Namespace
metadata:
  name: fcs-infra
  labels:
    app.kubernetes.io/part-of: fcs
    environment: local
---
apiVersion: v1
kind: Namespace
metadata:
  name: fcs-identity
  labels:
    app.kubernetes.io/part-of: fcs
    environment: local
---
apiVersion: v1
kind: Namespace
metadata:
  name: fcs-campaign
  labels:
    app.kubernetes.io/part-of: fcs
    environment: local
---
apiVersion: v1
kind: Namespace
metadata:
  name: fcs-donations
  labels:
    app.kubernetes.io/part-of: fcs
    environment: local
---
apiVersion: v1
kind: Namespace
metadata:
  name: fcs-donation-worker
  labels:
    app.kubernetes.io/part-of: fcs
    environment: local
---
apiVersion: v1
kind: Namespace
metadata:
  name: fcs-audit-logs
  labels:
    app.kubernetes.io/part-of: fcs
    environment: local
---
apiVersion: v1
kind: Namespace
metadata:
  name: fcs-web
  labels:
    app.kubernetes.io/part-of: fcs
    environment: local
