apiVersion: v1
kind: ConfigMap
metadata:
  name: fcs-identity-local-config
  namespace: fcs-identity
  labels:
    app.kubernetes.io/name: fcs-identity
    environment: local
data:
  ASPNETCORE_ENVIRONMENT: "Docker"
  ASPNETCORE_URLS: "http://+:8080"
  KafkaSettings__BootstrapServers: "kafka-service.fcs-infra.svc.cluster.local:29092"
  KafkaSettings__TopicName: "audit-log-requested"
  Keycloak__BaseUrl: "http://keycloak-service.fcs-infra.svc.cluster.local:8080"
  Keycloak__Realm: "conexao-solidaria"
  Keycloak__ClientId: "solidarity-api"
  Keycloak__AdminRealm: "master"
  Keycloak__AdminClientId: "admin-cli"
  Keycloak__AdminUsername: "admin"
  ManagerSeed__Enabled: "true"
  ManagerSeed__FullName: "Gestor ONG"
  ManagerSeed__Email: "gestor@conexaosolidaria.local"
  Observability__ServiceName: "Fcs.Identity"
  Observability__EnableOtlpExporter: "true"
  Observability__OtlpEndpoint: "http://otel-collector-service.fcs-infra.svc.cluster.local:4318"
  Observability__OtlpAuthHeader: ""
