http:
  middlewares:
    fcs-redirect-https:
      redirectScheme:
        scheme: https
  routers:
    fcs-http:
      entryPoints: [http]
      rule: Host(`fcs-web.flaviojcf.com.br`) || Host(`fcs-bff.flaviojcf.com.br`) || Host(`fcs-identity.flaviojcf.com.br`) || Host(`fcs-campaign.flaviojcf.com.br`) || Host(`fcs-donations.flaviojcf.com.br`) || Host(`fcs-keycloak.flaviojcf.com.br`) || Host(`fcs-kafka.flaviojcf.com.br`)
      middlewares: [fcs-redirect-https]
      service: fcs-k3s
    fcs-https:
      entryPoints: [https]
      rule: Host(`fcs-web.flaviojcf.com.br`) || Host(`fcs-bff.flaviojcf.com.br`) || Host(`fcs-identity.flaviojcf.com.br`) || Host(`fcs-campaign.flaviojcf.com.br`) || Host(`fcs-donations.flaviojcf.com.br`) || Host(`fcs-keycloak.flaviojcf.com.br`) || Host(`fcs-kafka.flaviojcf.com.br`)
      service: fcs-k3s
      tls:
        certResolver: letsencrypt
        domains:
          - main: fcs-web.flaviojcf.com.br
          - main: fcs-bff.flaviojcf.com.br
          - main: fcs-identity.flaviojcf.com.br
          - main: fcs-campaign.flaviojcf.com.br
          - main: fcs-donations.flaviojcf.com.br
          - main: fcs-keycloak.flaviojcf.com.br
          - main: fcs-kafka.flaviojcf.com.br
  services:
    fcs-k3s:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: http://host.docker.internal:32080
