apiVersion: v1
kind: ServiceAccount
metadata:
  name: fcs-identity-deployer
  namespace: fcs-identity
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fcs-identity-deployer
  namespace: fcs-identity
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fcs-identity-deployer
  namespace: fcs-identity
subjects:
  - kind: ServiceAccount
    name: fcs-identity-deployer
    namespace: fcs-identity
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fcs-identity-deployer
